---
- name: Deploy Kubernetes Application
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - name: Ensure namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: prod
        state: present

    - name: Deploy sample application
      kubernetes.core.k8s:
        state: present
        namespace: prod
        src: k8s/deployment.yaml


